version: '3.8'
services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        # command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000 # new
        environment: 
            - SECRET_KEY==43pv^43))2nfdubdd!)b8t^p+6-1-48w2urjg)z1rv2ay)7(d
            - DEBUG=1
            - POSTGRES_PASSWORD=postgres
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        links:
            - db:db
    db:
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: