# Generated by Django 3.1.1 on 2020-11-12 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventories.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelcomponents', to='inventories.car_model')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelengines', to='inventories.car_model')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelfuels', to='inventories.car_model')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='inventories.engine')),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prod_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), inventories.models.max_value_current_year])),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelyears', to='inventories.car_model')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelyears', to='inventories.make')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='pics/')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelparts', to='inventories.car_model')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentparts', to='inventories.component')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineparts', to='inventories.engine')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelparts', to='inventories.fuel')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeparts', to='inventories.make')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearparts', to='inventories.model_year')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carfuels', to='inventories.make'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearfuels', to='inventories.model_year'),
        ),
        migrations.AddField(
            model_name='engine',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carengines', to='inventories.make'),
        ),
        migrations.AddField(
            model_name='engine',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='inventories.model_year'),
        ),
        migrations.AddField(
            model_name='component',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enginecomponents', to='inventories.engine'),
        ),
        migrations.AddField(
            model_name='component',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelcomponents', to='inventories.fuel'),
        ),
        migrations.AddField(
            model_name='component',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carcomponents', to='inventories.make'),
        ),
        migrations.AddField(
            model_name='component',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearcomponents', to='inventories.model_year'),
        ),
        migrations.AddField(
            model_name='car_model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='inventories.make'),
        ),
    ]
