# Generated by Django 3.1.1 on 2020-09-23 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventories.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), inventories.models.max_value_current_year])),
                ('engine', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventories.car')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='pics/')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventories.component')),
            ],
        ),
    ]
